# shellcheck shell=sh

export PATH="${PATH}:/home/my_user/bin"

export CARGO_BIN_HOME="${CARGO_DATA_HOME}/bin"
export CARGO_CACHE_HOME="${XDG_CACHE_HOME}/cargo"
export CARGO_CONFIG_HOME="${XDG_CONFIG_HOME}/cargo"
export CARGO_DATA_HOME="${XDG_DATA_HOME}/cargo"
export CARGO_HOME="${XDG_DATA_HOME}/cargo"
export CUDA_CACHE_PATH="${XDG_CACHE_HOME}/cuda"
export DOTNET_CLI_HOME="${XDG_DATA_HOME}/dotnet"
export GNUPGHOME="${XDG_DATA_HOME}/gnupg"
export GOPATH="${XDG_DATA_HOME}/go"
export NUGET_PACKAGES="${XDG_CACHE_HOME}/NugetPackages"
export OLLAMA_MODELS="${XDG_DATA_HOME}/ollama/models"
export RUSTUP_CACHE_HOME="${XDG_CACHE_HOME}/rustup"
export RUSTUP_CONFIG_HOME="${XDG_CONFIG_HOME}/rustup"
export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
export STARSHIP_CACHE="${XDG_CACHE_HOME}/starship"
export STARSHIP_CONFIG="${XDG_CONFIG_HOME}/starship.toml"
export VSCODE_EXTENSIONS="${XDG_DATA_HOME}/vscode/extensions"
export VSCODE_PORTABLE="${XDG_DATA_HOME}/vscode"
export VSCODE_PORTABLE="${XDG_DATA_HOME}/vscode"
export WGETRC="${XDG_CONFIG_HOME}/wgetrc"
export XAUTHORITY="${XDG_RUNTIME_DIR}/Xauthority"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=${XDG_CONFIG_HOME}/java"
